### ISSUE TITLE
Add images to the wiki

### ISSUE THREAD

**Issue by damianofalcioni** [ADOxx-org/KpiDashboard-MM#1]
post the images here as a comment and then reference them:
![image](https://user-images.githubusercontent.com/8982949/27325994-7b1ac926-55aa-11e7-897c-0b8ca8b3b112.png)

url: https://user-images.githubusercontent.com/8982949/27325994-7b1ac926-55aa-11e7-897c-0b8ca8b3b112.png

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27329302-05c4f6be-556a-11e7-9024-572287f4addc.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27329359-2c489e08-556a-11e7-902e-5f7a07f8aef3.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27330635-273e73c4-556f-11e7-9f8c-4b7965b50dec.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27330719-777fce46-556f-11e7-9538-9e5867aeb4a2.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27330818-d89cab4a-556f-11e7-92a8-776509df827f.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27330867-fb6a6234-556f-11e7-84d4-fd9993dbf93c.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27332781-338eeb6e-5578-11e7-8031-48d34d868a74.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27332948-ecf87f84-5578-11e7-97cb-a69f7831d974.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27332976-03e08d72-5579-11e7-9ab7-24df12d6f85c.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27424177-fc5592ac-56e8-11e7-9236-18997be0b88d.png)
![image](https://user-images.githubusercontent.com/29372157/27424250-432dd2d4-56e9-11e7-876a-7554c1c15c8e.png)
![image](https://user-images.githubusercontent.com/29372157/27424862-594895a2-56eb-11e7-88bd-e19ad6c13ba0.png)
![image](https://user-images.githubusercontent.com/29372157/27424883-701e8584-56eb-11e7-8914-3c0578f71dd7.png)
![image](https://user-images.githubusercontent.com/29372157/27425047-f9a7ca2c-56eb-11e7-8fe2-8affe5f0d088.png)
![image](https://user-images.githubusercontent.com/29372157/27425075-12816bde-56ec-11e7-87e0-8c18d52598ad.png)
![image](https://user-images.githubusercontent.com/29372157/27425573-b1d7f3d2-56ed-11e7-8bf4-690f4a23d10e.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27424097-bcd9c224-56e8-11e7-94bd-fc7cc6fc86de.png)
![image](https://user-images.githubusercontent.com/29372157/27424103-c4c5cb2c-56e8-11e7-9a58-bcf59f730a8e.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27425799-76c5405a-56ee-11e7-841f-7bfce03f3520.png)

![image](https://user-images.githubusercontent.com/29372157/27426841-cb98c4e6-56f1-11e7-8546-959193918a14.png)
![image](https://user-images.githubusercontent.com/29372157/27427763-00e25056-56f5-11e7-8faa-73558e9494d5.png)
![image](https://user-images.githubusercontent.com/29372157/27427773-074bd69c-56f5-11e7-8295-b576867eac4b.png)
![image](https://user-images.githubusercontent.com/29372157/27427781-0e50dfa0-56f5-11e7-8182-dcf7595b7179.png)
![image](https://user-images.githubusercontent.com/29372157/27427789-14a7ce40-56f5-11e7-89ad-8c2cfb6a96da.png)
![image](https://user-images.githubusercontent.com/29372157/27427801-1b907dce-56f5-11e7-836b-3232bcbd27cd.png)
![image](https://user-images.githubusercontent.com/29372157/27427815-21c4e586-56f5-11e7-9763-1b528c4f47ce.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27429633-94f10ff8-56fa-11e7-806d-56cd8453bfc2.png)
![image](https://user-images.githubusercontent.com/29372157/27430382-335416f2-56fd-11e7-87fa-ea158703dd00.png)
![image](https://user-images.githubusercontent.com/29372157/27430782-be2046ce-56fe-11e7-97f3-a56bcb54c08d.png)
![image](https://user-images.githubusercontent.com/29372157/27430847-016e46d8-56ff-11e7-90fd-25ddf124fc3a.png)

![image](https://user-images.githubusercontent.com/29372157/27430948-5e4e4312-56ff-11e7-8f5b-b7c8e13d54a9.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27431059-f17d9886-56ff-11e7-8eb9-44eacaf4a64a.png)
![image](https://user-images.githubusercontent.com/29372157/27431083-03fb903a-5700-11e7-9e06-785170847ce2.png)
![image](https://user-images.githubusercontent.com/29372157/27431087-094e46d6-5700-11e7-828a-c14a9736346c.png)

![image](https://user-images.githubusercontent.com/29372157/27431239-a5872540-5700-11e7-9c38-4d5b072db3f3.png)
![image](https://user-images.githubusercontent.com/29372157/27431245-aae1bf50-5700-11e7-920d-29b22bffeaa8.png)
![image](https://user-images.githubusercontent.com/29372157/27431249-ae7a0140-5700-11e7-96a1-24fe47bdc1d9.png)
![image](https://user-images.githubusercontent.com/29372157/27431259-b618a37a-5700-11e7-9c3d-4d1015f16604.png)

![image](https://user-images.githubusercontent.com/29372157/27431494-9bd83538-5701-11e7-97b7-8a7a2cc85776.png)
![image](https://user-images.githubusercontent.com/29372157/27431500-a02db14e-5701-11e7-9205-8c0567f0768c.png)
![image](https://user-images.githubusercontent.com/29372157/27431540-c1b65df2-5701-11e7-953d-2cc78e9dba6b.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27431701-458dfcac-5702-11e7-924f-4ad9dc141d58.png)
![image](https://user-images.githubusercontent.com/29372157/27431727-5cad83d0-5702-11e7-9038-5518bb655803.png)
![image](https://user-images.githubusercontent.com/29372157/27431714-50b8998e-5702-11e7-94a8-e67fcbd98fbd.png)

![image](https://user-images.githubusercontent.com/29372157/27432106-b1bdea08-5703-11e7-844c-d7638a14c8fd.png)
![image](https://user-images.githubusercontent.com/29372157/27432110-b5588646-5703-11e7-8c14-63fe9777b77e.png)
![image](https://user-images.githubusercontent.com/29372157/27432113-b921816a-5703-11e7-9a96-9f254074d4dc.png)

![image](https://user-images.githubusercontent.com/29372157/27432325-9358e13e-5704-11e7-8df2-ec75c0683178.png)
![image](https://user-images.githubusercontent.com/29372157/27432343-a47ff182-5704-11e7-970c-8b9004cbc379.png)
![image](https://user-images.githubusercontent.com/29372157/27432360-b0069b6e-5704-11e7-9e3b-7a90616631db.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27432904-1e489512-5707-11e7-9440-4dfe609d4926.png)
![image](https://user-images.githubusercontent.com/29372157/27432923-30c71b96-5707-11e7-858c-df490aade0c2.png)
![image](https://user-images.githubusercontent.com/29372157/27432930-39f69b74-5707-11e7-9ebc-c5a705d2d7a5.png)

**Comment by Fredrake** [comment]
![image](https://user-images.githubusercontent.com/29372157/27433491-d6526776-5709-11e7-9d09-fb0e9e2c43c8.png)
![image](https://user-images.githubusercontent.com/29372157/27433497-de23134c-5709-11e7-9eff-b17599239a74.png)
![image](https://user-images.githubusercontent.com/29372157/27433505-e2d87bf2-5709-11e7-88f2-52a62f775a6c.png)

![image](https://user-images.githubusercontent.com/29372157/27433811-0dc5b090-570b-11e7-8a8d-3238b9253cb1.png)
![image](https://user-images.githubusercontent.com/29372157/27433875-553b637a-570b-11e7-8b66-9bf0ec657911.png)

**Comment by damianofalcioni** [comment]
![image](https://user-images.githubusercontent.com/8982949/46816755-eddba100-cd7d-11e8-8ba4-62d1e61d2dca.png)

**Comment by damianofalcioni** [comment]
![image](https://user-images.githubusercontent.com/8982949/46816985-693d5280-cd7e-11e8-9685-6c839ee1ffa9.png)

**Comment by damianofalcioni** [comment]
![image](https://user-images.githubusercontent.com/8982949/46817309-2c259000-cd7f-11e8-9149-0c68b02330fe.png)

**Comment by damianofalcioni** [comment]
![image](https://user-images.githubusercontent.com/8982949/46817594-a35b2400-cd7f-11e8-99b5-64c773e83d3f.png)
